### ISSUE TITLE
Batch keyloading

### ISSUE THREAD

**Issue by P25phase2** [duggerd/KFDtool#14] opened 2019-10-31 23:04 UTC
Devise a method to batch load all 32 keys into Keyset 1 and 2

**Comment by mattames** [comment] 2019-10-31 23:25
This is essentially a duplicate of Issue #2 -  https://github.com/duggerd/KFDtool/issues/2

**Comment by P25phase2** [comment] 2019-10-31 23:55
Missed it in the issue log, thanks.

**Closed** 2019-11-05 16:43 UTC
Labels: duplicate
